### ISSUE TITLE
domain-specific: bid/ask and primary/counter

### ISSUE THREAD

**Issue by adlai** [adishavit/equisized_antonyms#16]
In financial markets, there could be lots of assets traded in some venue; any quoted price is the price of one asset in terms of another. For a specific market between two assets, the primary asset is the numerator, and the counter is the denominator; quite literally, `primary/counter`.

There is also `bid/ask`, which are sibling subtypes of offer although frequently show up in source code as mutually opposed; bids and asks are the offers to buy and offers to sell, respectively.

Is either pair worth a PR?

**Comment by adishavit** [comment]
Of course. PR please 🙏.
