### ISSUE TITLE
`OK`/`NG`

### ISSUE THREAD

**Issue by nmatt** [adishavit/equisized_antonyms#7]
The pair `OK`/`NG` (Not Good) could be added. It's certainly not widely used (except maybe in Japan), but not worse than `yeah`/`nope` either.

References:
https://en.wiktionary.org/wiki/NG#Adjective
https://www.quora.com/When-and-how-did-the-Japanese-abbreviation-NG-meaning-Not-good-or-Not-OK-a-counterpart-to-OK-originate

**Comment by adishavit** [comment]
Interesting. I was not familiar with this.
Make a PR in the Oddballs section and add the ref.
